# Generated by Django 3.1 on 2020-08-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='news_source',
            field=models.CharField(default='bbc-news', max_length=50),
        ),
    ]
